### ISSUE TITLE
Malfunction over plurals

### ISSUE THREAD

**Issue by LeonPyramid** [remimorvan/knowledge-clustering#10]
If a plural isn't defined in my knowledge{notation}, the word will be quoted with its s out. For example i have a knowledge for the word pattern, and patterns will be quoted as "pattern"s

**Comment by remimorvan** [comment]
This is not a bug: as it is, knowledge-clustering does not try to infer what should/could be an interesting notion: this is the job of the user ; knowledge-clustering reads the notions either in the file defining notions or in the diagnose file. Adding an option to suggest new notions in very simple cases (e.g. notions limited to a single word, as in your example) could be interesting.

**Comment by remimorvan** [comment]
The suggestion was implemented in v0.5.0.
