### ISSUE TITLE
Improve CLI interface

### ISSUE THREAD

**Issue by AliaumeL** [remimorvan/knowledge-clustering#5]
Several options can improve the CLI interface

1. Remove the need to have a call to `cluster` as it is the most used command. This can be done via https://github.com/click-contrib/click-default-group
2. Revert to using tex/diagnose options instead of file arguments ? 
3. Use a `detect` option to avoid filling the filenames

**Comment by remimorvan** [comment]
The first two suggestions are implemented in [v0.2.3](https://github.com/remimorvan/knowledge-clustering/releases/tag/v0.2.3). The third suggestion is a good idea: we should also add the possibility of having multiple notion files.
